Signing use archive temproot for DirectoryHash to avoid cross-device renames.
We are throwing the below errors trying to handle directory hashing of
the now installed custom uploads.  Move to using the archive temproot
for storage of the checksum files while they are being constructed.
This is in line with the other users of RepositoryIndexFile().

 OSError: [Errno 18] Invalid cross-device link

    Traceback (most recent call last):
  Module lp.archivepublisher.scripts.processaccepted, line 85, in processQueueItem
    queue_item.realiseUpload(self.logger)
  Module lp.soyuz.model.queue, line 785, in realiseUpload
    customfile.publish(logger)
  Module lp.soyuz.model.queue, line 1359, in publish
    self.packageupload, self.libraryfilealias, logger=logger)
  Module lp.archivepublisher.customupload, line 112, in publish
    upload.process(packageupload.archive, tarfile_path, suite)
  Module lp.archivepublisher.customupload, line 131, in process
    self.installFiles()
  Module lp.archivepublisher.signing, line 342, in installFiles
    hasher.add_dir(versiondir)
  Module lp.archivepublisher.publishing, line 1496, in __exit__
    self.close()
  Module lp.archivepublisher.publishing, line 1526, in close
    checksum_file.close()
  Module lp.archivepublisher.utils, line 169, in close
    os.rename(index_file.path, root_path)

Signed-off-by: Andy Whitcroft <apw@ubuntu.com>